export const CANCELED_RESERVATION_EMITTER_MESSAGE = "CANCELED_RESERVATION";
export const ngrok = "https://5902-45-243-244-41.ngrok-free.app"
export const SLOT_STATUS_CHANGED_MESSAGE = "SLOT_STATUS_CHANGED"